use serde::{Deserialize, Serialize};
use std::time::SystemTime;
use crate::models::hardware::{HardwareStatus, SensorType};

/// Per-device health information that is exposed to the dashboard HTML.
///
/// This struct is serialized to JSON and consumed directly by
/// `static/dashboard.html` to render the Devices Console table and
/// detail panel. Any new fields added here should remain backwards
/// compatible with existing producers and consumers.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DeviceHealth {
    /// Unique numeric identifier of the device.
    pub device_id: u32,
    /// Human readable name of the device.
    pub device_name: String,
    /// Current hardware status (online / offline / maintenance / etc.).
    pub status: HardwareStatus,
    /// Last point in time the server observed this device.
    pub last_seen: SystemTime,
    /// Uptime percentage over the configured window.
    pub uptime_percentage: f64,
    /// Optional battery level in percent (0-100).
    pub battery_level: Option<f64>,
    /// Optional signal strength in percent (0-100).
    pub signal_strength: Option<f64>,
    /// Firmware version string reported by the device.
    pub firmware_version: String,
    /// Optional last known physical location of the device.
    pub location: Option<crate::models::hardware::Location>,

    /// Logical operating mode of the device as controlled from the console.
    ///
    /// When set to `"development"` the server can treat this device as
    /// non-production and, for example, ignore its metrics for uptime or
    /// alert statistics. When `None` the server should treat the device as
    /// production by default.
    #[serde(default)]
    pub mode: Option<String>,

    /// Whether the server should accept and process heartbeats
    /// originating from this device.
    ///
    /// `Some(false)` means heartbeats from this device may be ignored for
    /// monitoring and uptime calculations. `None` or `Some(true)` means
    /// they are processed normally.
    #[serde(default)]
    pub heartbeat_enabled: Option<bool>,

    /// Whether the server should accept and process MQTT telemetry
    /// originating from this device.
    ///
    /// `Some(false)` means MQTT messages from this device may be ignored.
    /// `None` or `Some(true)` means messages are processed normally.
    #[serde(default)]
    pub mqtt_enabled: Option<bool>,
}

/// Single activity entry related to a specific device.
///
/// This is used to build short activity timelines in the dashboard.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct DeviceActivity {
    /// Device that generated the activity.
    pub device_id: u32,
    /// High-level type of the activity.
    pub activity_type: ActivityType,
    /// When the activity occurred.
    pub timestamp: SystemTime,
    /// Free-text description for the UI.
    pub details: String,
    /// Optional data size associated with the activity (bytes, etc.).
    pub data_size: Option<usize>,
}

/// Enumeration of activity types that can appear in the dashboard.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "PascalCase")]
pub enum ActivityType {
    DataSent,
    AlertTriggered,
    CommandReceived,
    StatusChange,
    StatusUpdate,
    Heartbeat,
    ImageCaptured,
    ConfigUpdate,
}

/// Top-level overview metrics for the dashboard summary cards.
#[derive(Debug, Serialize, Deserialize)]
pub struct DashboardOverview {
    /// Total number of devices registered in the system.
    pub total_devices: u32,
    /// Devices that are currently considered online.
    pub online_devices: u32,
    /// Devices that are currently considered offline.
    pub offline_devices: u32,
    /// Number of devices that have at least one active alert.
    pub devices_with_alerts: u32,
    /// Total alerts triggered in the last 24 hours.
    pub total_alerts_today: u32,
    /// Total data received from all devices (megabytes).
    pub total_data_received_mb: f64,
    /// Average uptime across all devices.
    pub average_uptime: f64,
    /// When these overview metrics were last computed.
    pub last_updated: SystemTime,
}

/// Per-device metrics that are more detailed than `DeviceHealth`.
///
/// These values are typically used for charts or deeper analysis.
#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceMetrics {
    /// Device identifier this metrics record belongs to.
    pub device_id: u32,
    /// Optional CPU utilisation percentage.
    pub cpu_usage: Option<f64>,
    /// Optional memory utilisation percentage.
    pub memory_usage: Option<f64>,
    /// Optional temperature reading in degrees Celsius.
    pub temperature: Option<f64>,
    /// Total data sent by this device in megabytes.
    pub data_sent_mb: f64,
    /// Number of alerts generated by this device.
    pub alerts_count: u32,
    /// Activity entries within the last 24 hours.
    pub last_24h_activity: Vec<DeviceActivity>,
}

/// Simplified representation of an alert for use in lists/tables.
#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct AlertSummary {
    /// Unique identifier of the alert (database ID).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<u32>,
    /// Legacy alert_id field for backwards compatibility.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub alert_id: Option<String>,
    /// Device that generated the alert.
    pub device_id: u32,
    /// Human readable device name.
    pub device_name: String,
    /// Short alert message.
    pub message: String,
    /// Severity level of the alert.
    pub severity: AlertSeverity,
    /// When the alert occurred.
    pub timestamp: SystemTime,
    /// Whether the alert has been acknowledged in the UI.
    pub acknowledged: bool,
    /// Optional path to an image related to the alert (if available).
    pub image_path: Option<String>,
}

/// Alert severity levels exposed to the dashboard.
#[derive(Debug, Serialize, Deserialize, Clone)]
#[serde(rename_all = "snake_case")]
pub enum AlertSeverity {
    Low,
    Medium,
    High,
    Critical,
}

/// Full payload returned by `GET /api/v1/dashboard`.
///
/// This aggregates multiple slices of information that the frontend uses
/// to render the console and overview screens.
#[derive(Debug, Serialize, Deserialize)]
pub struct DashboardData {
    /// High-level aggregated metrics.
    pub overview: DashboardOverview,
    /// Per-device health snapshot.
    pub device_health: Vec<DeviceHealth>,
    /// Recent alerts across the system.
    pub recent_alerts: Vec<AlertSummary>,
    /// Optional metrics per device.
    pub device_metrics: Vec<DeviceMetrics>,
}

/// Filter object that can be used to query subsets of devices.
#[derive(Debug, Serialize, Deserialize)]
pub struct DeviceFilter {
    /// Optional filter by status.
    pub status: Option<HardwareStatus>,
    /// Optional filter by primary sensor type.
    pub sensor_type: Option<SensorType>,
    /// Optional circular area filter (lat, lon, radius_km).
    pub location_radius: Option<(f64, f64, f64)>, // lat, lon, radius_km
    /// Optional filter on last seen time, in hours.
    pub last_seen_hours: Option<u32>,
}

/// Simple time range type used by some dashboard queries.
#[derive(Debug, Serialize, Deserialize)]
pub struct TimeRange {
    /// Start of the time range (inclusive).
    pub start: SystemTime,
    /// End of the time range (inclusive or exclusive depending on context).
    pub end: SystemTime,
}
